### ISSUE TITLE
Chicken & Egg?

### ISSUE THREAD

**Issue by kheiman61** [jlattimer/CrmAzureKeyVaultExample#1]
Doesn't storing the client id / secret / tenant id in the code sort of just abstract the problem one level? If someone can get those values, can't they then access your secrets?

**Comment by jlattimer** [comment]
Isn't that the same problem everywhere though? Until something better is actually built into CRM at the tenant level you're going to end up trading off between security, performance, or manageability.

**Comment by kheiman61** [comment]
Yeah that's fair, I've just been frustrated that there's no more seamless way to meld Dynamics 365 with KeyVault. It's not really an 'issue' with the code, I just couldn't find a way to comment on the blog :)
