### ISSUE TITLE
Should not be storing secrets in your code!

### ISSUE THREAD

**Issue by aakshayb** [jlattimer/CrmAzureKeyVaultExample#2]
How is it a good idea to store client Id and client secret in your plugin code? Anyone with access to the plugin (everyone in that instance of CRM) can download your dll, decompile it and use your secrets to access your not so secret key vault??

**Comment by jlattimer** [comment]
This is just sample code - chill

**Comment by aakshayb** [comment]
Haha sample code for how it shouldn't be done , to be precise

**Comment by jlattimer** [comment]
Sure thing troll
